[env:epiper_esp32s3]
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200

; Explicit 8MB Flash mapping
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

; Force hardware PSRAM initialization
build_flags = 
    -DBOARD_HAS_PSRAM

lib_deps =
    zinggjm/GxEPD2 @ ^1.5.8
    https://github.com/takkaO/OpenFontRender.git